# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crusoe < Formula
  desc "Software to manage carbon negative computing infrastructure running on Crusoe Cloud"
  homepage "https://crusoecloud.com/"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crusoecloud/cli/releases/download/v1.0.8/crusoe_Darwin_x86_64.tar.gz"
      sha256 "952e22ffbdbab8f1d9c20caa78eb8e43bd90040c0e9d6e0f2911da7cde159829"

      define_method(:install) do
        bin.install "crusoe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crusoecloud/cli/releases/download/v1.0.8/crusoe_Darwin_arm64.tar.gz"
      sha256 "a2479af7c444d490ea66cff7ca49a349d0599be0b88468434851943037862030"

      define_method(:install) do
        bin.install "crusoe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crusoecloud/cli/releases/download/v1.0.8/crusoe_Linux_x86_64.tar.gz"
      sha256 "240a416829f39e6763af60fa62dfe987254f75a85429130020f5ed8e5019d0e9"
      define_method(:install) do
        bin.install "crusoe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crusoecloud/cli/releases/download/v1.0.8/crusoe_Linux_arm64.tar.gz"
      sha256 "e763d22485c588c73299e9a0b224f8baba847f2b21de8a229e832ac35fa20d1c"
      define_method(:install) do
        bin.install "crusoe"
      end
    end
  end
end
