# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crusoe < Formula
  desc "Software to manage carbon negative computing infrastructure running on Crusoe Cloud"
  homepage "https://crusoecloud.com/"
  version "0.31.30"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crusoecloud/cli/releases/download/v0.31.30/crusoe_Darwin_x86_64.tar.gz"
      sha256 "4f8598fcd7eca9473c660559e245df7fc545aac123c932521204532214ce3ef9"

      define_method(:install) do
        bin.install "crusoe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crusoecloud/cli/releases/download/v0.31.30/crusoe_Darwin_arm64.tar.gz"
      sha256 "866403b65e75291146672f82001d69ba9ab4b6b98c428d128bdc278b2f398bdd"

      define_method(:install) do
        bin.install "crusoe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crusoecloud/cli/releases/download/v0.31.30/crusoe_Linux_x86_64.tar.gz"
      sha256 "b727b5174f828a62744262430e0498873694989e8b8a3f4cc9cc1e19102f9401"
      define_method(:install) do
        bin.install "crusoe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crusoecloud/cli/releases/download/v0.31.30/crusoe_Linux_arm64.tar.gz"
      sha256 "c026369b2ca517a9bab8439707a782a13b855720b5e768583b0df439d0011343"
      define_method(:install) do
        bin.install "crusoe"
      end
    end
  end
end
