# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crusoe < Formula
  desc "Software to manage carbon negative computing infrastructure running on Crusoe Cloud"
  homepage "https://crusoecloud.com/"
  version "0.31.25"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crusoecloud/cli/releases/download/v0.31.25/crusoe_Darwin_x86_64.tar.gz"
      sha256 "862d2526e410f4c9ce508f061391519e96ed94fc4247e73a376ace94ac1f6fe0"

      def install
        bin.install "crusoe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crusoecloud/cli/releases/download/v0.31.25/crusoe_Darwin_arm64.tar.gz"
      sha256 "9d53720bcf9f3d82589757c14a6b36ec090a26129dffc884b0fbb6d732fbfa0d"

      def install
        bin.install "crusoe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crusoecloud/cli/releases/download/v0.31.25/crusoe_Linux_x86_64.tar.gz"
      sha256 "5e4aca3faa7c2bafbbc352c19ea2b0ec87e99b5df4d1cba123d9493b69d2b655"
      def install
        bin.install "crusoe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crusoecloud/cli/releases/download/v0.31.25/crusoe_Linux_arm64.tar.gz"
      sha256 "f99e7b6aad0f91faeec106fcd8f6ca2c56d01df3bf6b2d0463e28e63ae436e48"
      def install
        bin.install "crusoe"
      end
    end
  end
end
